### ISSUE TITLE
create an account

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/5Guys1Code#1]
**description:** <br>
As a user, I want to be able to create an account, so that I can be able to log in and use the application. 

**Acceptance criteria**: <br>
   1.	users can create user-name and password
   2.	user can change password
   3.	send email confirmation upon account creation 

Story source: 09/26/2017

Estimate: 7 man-hours

**Comment by JimmyHowellSIU** [comment]
The login functionality works to communicate with our database.
